//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordScrambleClient.WordScrambleGameServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameAlreadyBeingHostedException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
    [System.SerializableAttribute()]
    public partial class GameAlreadyBeingHostedException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currentHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currentHost {
            get {
                return this.currentHostField;
            }
            set {
                if ((object.ReferenceEquals(this.currentHostField, value) != true)) {
                    this.currentHostField = value;
                    this.RaisePropertyChanged("currentHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scrambledWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unscrambledWordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scrambledWord {
            get {
                return this.scrambledWordField;
            }
            set {
                if ((object.ReferenceEquals(this.scrambledWordField, value) != true)) {
                    this.scrambledWordField = value;
                    this.RaisePropertyChanged("scrambledWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unscrambledWord {
            get {
                return this.unscrambledWordField;
            }
            set {
                if ((object.ReferenceEquals(this.unscrambledWordField, value) != true)) {
                    this.unscrambledWordField = value;
                    this.RaisePropertyChanged("unscrambledWord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HostCannotJoinGameException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
    [System.SerializableAttribute()]
    public partial class HostCannotJoinGameException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameNotBeingHostedException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
    [System.SerializableAttribute()]
    public partial class GameNotBeingHostedException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaxmimumPlayersReachedException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
    [System.SerializableAttribute()]
    public partial class MaxmimumPlayersReachedException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maxPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxPlayers {
            get {
                return this.maxPlayersField;
            }
            set {
                if ((this.maxPlayersField.Equals(value) != true)) {
                    this.maxPlayersField = value;
                    this.RaisePropertyChanged("maxPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserNotInGameException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
    [System.SerializableAttribute()]
    public partial class UserNotInGameException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordScrambleGameServiceReference.IWordScrambleGame")]
    public interface IWordScrambleGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/isGameBeingHosted", ReplyAction="http://tempuri.org/IWordScrambleGame/isGameBeingHostedResponse")]
        bool isGameBeingHosted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/isGameBeingHosted", ReplyAction="http://tempuri.org/IWordScrambleGame/isGameBeingHostedResponse")]
        System.Threading.Tasks.Task<bool> isGameBeingHostedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/hostGame", ReplyAction="http://tempuri.org/IWordScrambleGame/hostGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WordScrambleClient.WordScrambleGameServiceReference.GameAlreadyBeingHostedException), Action="http://tempuri.org/IWordScrambleGame/hostGameGameAlreadyBeingHostedExceptionFault" +
            "", Name="GameAlreadyBeingHostedException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
        string hostGame(string userName, string hostAddress, string wordToScramble);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/hostGame", ReplyAction="http://tempuri.org/IWordScrambleGame/hostGameResponse")]
        System.Threading.Tasks.Task<string> hostGameAsync(string userName, string hostAddress, string wordToScramble);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/join", ReplyAction="http://tempuri.org/IWordScrambleGame/joinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WordScrambleClient.WordScrambleGameServiceReference.HostCannotJoinGameException), Action="http://tempuri.org/IWordScrambleGame/joinHostCannotJoinGameExceptionFault", Name="HostCannotJoinGameException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
        [System.ServiceModel.FaultContractAttribute(typeof(WordScrambleClient.WordScrambleGameServiceReference.GameNotBeingHostedException), Action="http://tempuri.org/IWordScrambleGame/joinGameNotBeingHostedExceptionFault", Name="GameNotBeingHostedException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
        [System.ServiceModel.FaultContractAttribute(typeof(WordScrambleClient.WordScrambleGameServiceReference.MaxmimumPlayersReachedException), Action="http://tempuri.org/IWordScrambleGame/joinMaxmimumPlayersReachedExceptionFault", Name="MaxmimumPlayersReachedException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
        WordScrambleClient.WordScrambleGameServiceReference.Word join(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/join", ReplyAction="http://tempuri.org/IWordScrambleGame/joinResponse")]
        System.Threading.Tasks.Task<WordScrambleClient.WordScrambleGameServiceReference.Word> joinAsync(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/guessWord", ReplyAction="http://tempuri.org/IWordScrambleGame/guessWordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WordScrambleClient.WordScrambleGameServiceReference.UserNotInGameException), Action="http://tempuri.org/IWordScrambleGame/guessWordUserNotInGameExceptionFault", Name="UserNotInGameException", Namespace="http://schemas.datacontract.org/2004/07/MCAssign3Service")]
        bool guessWord(string playerName, string guessedWord, string unscrambledWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/guessWord", ReplyAction="http://tempuri.org/IWordScrambleGame/guessWordResponse")]
        System.Threading.Tasks.Task<bool> guessWordAsync(string playerName, string guessedWord, string unscrambledWord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordScrambleGameChannel : WordScrambleClient.WordScrambleGameServiceReference.IWordScrambleGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordScrambleGameClient : System.ServiceModel.ClientBase<WordScrambleClient.WordScrambleGameServiceReference.IWordScrambleGame>, WordScrambleClient.WordScrambleGameServiceReference.IWordScrambleGame {
        
        public WordScrambleGameClient() {
        }
        
        public WordScrambleGameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordScrambleGameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordScrambleGameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordScrambleGameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isGameBeingHosted() {
            return base.Channel.isGameBeingHosted();
        }
        
        public System.Threading.Tasks.Task<bool> isGameBeingHostedAsync() {
            return base.Channel.isGameBeingHostedAsync();
        }
        
        public string hostGame(string userName, string hostAddress, string wordToScramble) {
            return base.Channel.hostGame(userName, hostAddress, wordToScramble);
        }
        
        public System.Threading.Tasks.Task<string> hostGameAsync(string userName, string hostAddress, string wordToScramble) {
            return base.Channel.hostGameAsync(userName, hostAddress, wordToScramble);
        }
        
        public WordScrambleClient.WordScrambleGameServiceReference.Word join(string playerName) {
            return base.Channel.join(playerName);
        }
        
        public System.Threading.Tasks.Task<WordScrambleClient.WordScrambleGameServiceReference.Word> joinAsync(string playerName) {
            return base.Channel.joinAsync(playerName);
        }
        
        public bool guessWord(string playerName, string guessedWord, string unscrambledWord) {
            return base.Channel.guessWord(playerName, guessedWord, unscrambledWord);
        }
        
        public System.Threading.Tasks.Task<bool> guessWordAsync(string playerName, string guessedWord, string unscrambledWord) {
            return base.Channel.guessWordAsync(playerName, guessedWord, unscrambledWord);
        }
    }
}
